[package]
name = "sqlx-example-sqlite-todos"
version = "0.1.0"
edition = "2021"
publish = false
workspace = "../../../"

[dependencies]
anyhow = "1.0"
futures = "0.3"
sqlx = { version = "0.8", features = [ "runtime-tokio", "tls-native-tls" ] }
sqlx-libsql = { path = "../.." }
clap = { version = "4", features = ["derive"] }
tokio = { version = "1.20.0", features = ["rt", "macros"]}
tokio-stream = "0.1"
